### PR TITLE
Do not crash if resulting image is too big

### LINKED ISSUE #1650: Uploading extremely large images crashes z_file_entry
```erlang
{image_too_high,[{z_utils,assert,2,[{file,"src/support/z_utils.erl"},{line,496}]},{z_media_preview,convert_1,6,[{file,"src/support/z_media_preview.erl"},{line,87}]},{z_file_locate,generate_preview,7,[{file,"src/support/z_file_locate.erl"},{line,235}]},{z_file_locate,locate_source,5,[{file,"src/support/z_file_locate.erl"},{line,80}]},{z_file_locate,'-locate_sources/4-lc$^1/1-1-',3,[{file,"src/support/z_file_locate.erl"},{line,48}]},{z_file_entry,locate,2,[{file,"src/support/z_file_entry.erl"},{line,175}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
```

Proposed solution: return `{error, Reason}` from `z_utils:assert` instead of throwing the error. If `z_file_entry` receives `{error, Reason}`, serve an error image placeholder instead of the original image.

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Fix #1650 

Remove assertions on image size, return errors instead.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

File: src/support/z_media_preview.erl [hunk 1]
```diff
@@ -83,8 +83,15 @@ convert_1(false, _InFile, _OutFile, _Mime, _FileProps, _Filters) ->
...
-    z_utils:assert(EndWidth  < ?MAX_WIDTH, image_too_wide),
-    z_utils:assert(EndHeight < ?MAX_HEIGHT, image_too_high),
+    convert_2(EndWidth, EndHeight, CmdArgs, ConvertCmd, InFile, OutFile, Mime, FileProps).
+
+convert_2(EndWidth, _EndHeight, _CmdArgs, _ConvertCmd, _InFile, _OutFile, _Mime, _FileProps) 
+    when EndWidth > ?MAX_WIDTH ->
+    {error, image_too_wide};
+convert_2(_EndWidth, EndHeight, _CmdArgs, _ConvertCmd, _InFile, _OutFile, _Mime, _FileProps) 
+    when EndHeight > ?MAX_HEIGHT ->
+    {error, image_too_wide};
```
Comment (ddeboer) [inline src/support/z_media_preview.erl]: Should this be `image_too_high` instead?

Comment (mworrell) [inline src/support/z_media_preview.erl]: Or shall we both make `image_size` ?
Less cases to check on, and if there is some rotation then the width/height is unclear anyway.

Comment (ddeboer) [inline src/support/z_media_preview.erl]: Fine with me.
