### PR TITLE
mod_search: Fix #1895 by also splitting non-binaries

### LINKED ISSUE #1895: Search query parse edges crashes on stable.
Probably caused by your latest fix @ddeboer?

```
12:16:40.896 [warning] webmachine_mochiweb:221 caught error {stop_request,500,{function_clause,[{filter_stringify,stringify_1,[{function_clause,[{search_query,parse_edges,[hassubject,320,{search_sql,"rsc.id","rsc rsc",[],[],[],undefined,[{rsc,"rsc"}],[],[{"rsc",[<<"group">>]}],[],[],undefined,[],false},{context,channelwww
```

### PR DESCRIPTION
**Pull request by ddeboer**
From query pages, `hassubject=123` yields `{hassubject, <<"123">>}`.
From templates, however, `hassubject=123` yields `{hassubject, 123}`.
Consequently, we have to split both binaries and integers.

Ref #1894

### Description

Fix #1895.

Please describe here what the PR does.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

File: modules/mod_search/support/search_query.erl [hunk 1]
```diff
@@ -882,8 +882,6 @@ map_filter_operator(Op) -> throw({error, {unknown_filter_operator, Op}}).
 
 
 % Convert an expression like [123,hasdocument]
-maybe_split_list(Id) when is_integer(Id) ->
-    [Id];
```
Comment (ddeboer) [inline modules/mod_search/support/search_query.erl]: This cleanup seems harmless given the other cases.
