### PR TITLE
core: Untangle name_to_id and rid

### LINKED ISSUE #440: name_to_id does not work for resources which have names with all numbers
m_rsc:name_to_id simply returns the passed number as the resource id. 

All uses of name_to_id should be checked, because some of those uses could expect this behaviour. If this is the case, m_rsc:rid should be used instead.

### PR DESCRIPTION
**Pull request by ddeboer**
### Description

- Make m_rsc:name_to_id/2 stricter by removing implicit conversion from
  textual name to resource id integer.
- Remove digital name conversion from m_rsc:name/2:
- Remove name_to_id_check/2 from m_category, m_predicate and m_rsc to
  reduce confusion.

Fix #440.

### Checklist

- [x] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
Looks good to me.

Less is more!

File: src/models/m_edge.erl [hunk 1]
```diff
@@ -809,13 +816,13 @@ update_sequence(Id, Pred, ObjectIds, Context) ->
...
         true ->
-            PredId = m_predicate:name_to_id_check(Pred, Context),
+            {ok, PredId} = m_predicate:name_to_id(Pred, Context),
             F = fun(Ctx) ->
                 All = z_db:q("
                             select object_id, id
                             from edge
                             where predicate_id = $1
-                              and subject_id = $2", [PredId, m_rsc:name_to_id_check(Id, Context)], Ctx),
+                              and subject_id = $2", [PredId, m_rsc:rid(Id, Context)], Ctx),
```
Comment (mworrell) [inline src/models/m_edge.erl]: This will change the crash from Erlang to a database constraint error.  Which is ok with me.

Comment (ddeboer) [inline src/models/m_edge.erl]: I think the Erlang crash is clearer than some database constraint error, so fixed this.
