### PR TITLE
mod_wires: add optional href attribute for button with tag 'a'

### LINKED ISSUE #3784: Button scomp add href when using tag 'a'
When using the button scomp with a `tag='a'` the generated html misses an `href` attribute making this anchor tag an invalid html tag. Could we add this? And then maybe also remove the `type="button"` when using `tag='a'`.

Current behaviour:

`{% button text="Click me" tag="a" action={alert text="Hello Word!"} %}`
Generates:
`<a class="btn btn-default" type="button" id="rukhhc">Click me</a>`

Proposed behaviour
`{% button text="Click me" tag="a" action={alert text="Hello Word!"} %}`
Generates:
`<a href="#" class="btn btn-default"  id="rukhhc">Click me</a>`

What would also be nice is to maybe add an `href` attribute so we can give it a fallback when JS is not working.

`{% button text="Click me" tag="a" href="/bliep" action={alert text="Hello Word!"} %}`
Generates:
`<a href="/bliep" class="btn btn-default"  id="rukhhc">Click me</a>`

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Ensure that buttons with tag `a` have a `href` attribute.
Add it as an optional parameter for the `{% button %}` scomp.

Also make the default `Submit` text translatable.

Fix #3784 

### Checklist

- [x] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

File: apps/zotonic_mod_wires/src/scomps/scomp_wires_button.erl [hunk 1]
```diff
@@ -28,68 +28,70 @@ vary(_Params, _Context) -> nocache.
...
+        {<<"name">>,  case proplists:is_defined(id, Params) of true -> Id; false -> <<>> end},
         {<<"style">>, Style},
         {<<"title">>, Title},
         {<<"tabindex">>, TabIndex}
     ],
 
     {Class2, Attrs1} = case z_convert:to_bool(Disabled) of
         false -> {Class1, Attrs};
-        true -> { ["disabled"|Class1], [ {<<"disabled">>,"disabled"}|Attrs] }
+        true -> { [<<"disabled">>|Class1], [{<<"disabled">>,<<"disabled">>}|Attrs] }
```
Comment (vkatsuba) [inline apps/zotonic_mod_wires/src/scomps/scomp_wires_button.erl:77]: Minor:
```suggestion
        true -> { [<<"disabled">> | Class1], [{<<"disabled">>,<<"disabled">>} | Attrs] }
```

**Review by vkatsuba — APPROVED** [review]

File: apps/zotonic_mod_wires/src/scomps/scomp_wires_button.erl [hunk 2]
```diff
@@ -1,9 +1,9 @@
 %% @author Marc Worrell <marc@worrell.nl>
-%% @copyright 2009-2013 Marc Worrell
-%%
-%% Based on code (c) 2008-2009 Rusty Klophaus
+%% @copyright 2009-20124 Marc Worrell
```
Comment (DorienD) [inline apps/zotonic_mod_wires/src/scomps/scomp_wires_button.erl:2]: Tiny mistake ;)

Comment (vkatsuba) [reply apps/zotonic_mod_wires/src/scomps/scomp_wires_button.erl:2]: https://github.com/zotonic/zotonic/pull/3787 :face_in_clouds:
